# Generated by Django 6.0.7 on 2026-07-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.IntegerField(choices=[(5, '5 vs 5'), (7, '7 vs 7'), (11, '11 vs 11')], default=5)),
                ('surface', models.CharField(choices=[('SYNTHETIC', 'Synthetic Grass'), ('NATURAL', 'Natural Grass'), ('INDOOR', 'Indoor / Parquet')], default='SYNTHETIC', max_length=20)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
