# Generated by Django 6.0.7 on 2026-07-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['name'], name='fields_fiel_name_82fe28_idx'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['field_type'], name='fields_fiel_field_t_52b7e6_idx'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['is_active'], name='fields_fiel_is_acti_ed6a6b_idx'),
        ),
    ]
