# Generated by Django 6.0.7 on 2026-07-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_alter_field_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='fields/'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['deleted_at'], name='fields_fiel_deleted_cdc40e_idx'),
        ),
    ]
