services:
  - type: web
    name: kickcourt-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DB_NAME
        value: neondb
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        value: ep-frosty-glitter-axdmk6tc-pooler.c-4.us-east-2.aws.neon.tech
      - key: DB_PORT
        value: "5432"
      - key: DB_SSLMODE
        value: require
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        value: noreply@kickcourt.com
      - key: FRONTEND_URL
        sync: false
