# Generated by Django 6.0.7 on 2026-07-28 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sport_type', models.CharField(choices=[('FOOTBALL', 'Football'), ('PADEL', 'Padel'), ('TENNIS', 'Tennis'), ('BASKETBALL', 'Basketball'), ('VOLLEYBALL', 'Volleyball'), ('HOCKEY', 'Hockey')], default='FOOTBALL', max_length=20)),
                ('surface', models.CharField(choices=[('SYNTHETIC', 'Synthetic'), ('NATURAL', 'Natural Grass'), ('INDOOR', 'Indoor'), ('CLAY', 'Clay'), ('GRASS', 'Grass'), ('HARD', 'Hard Court'), ('WOOD', 'Wood'), ('SAND', 'Sand')], default='SYNTHETIC', max_length=20)),
                ('players_per_side', models.IntegerField(default=5)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='courts/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='vendors.vendor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourtBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='courts.court')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='CourtSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courts.court')),
            ],
            options={
                'ordering': ['court', 'day_of_week'],
            },
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['name'], name='courts_cour_name_39e975_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['sport_type'], name='courts_cour_sport_t_082085_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['is_active'], name='courts_cour_is_acti_bc541b_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['deleted_at'], name='courts_cour_deleted_8e9818_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courtschedule',
            unique_together={('court', 'day_of_week')},
        ),
    ]
