# Generated by Django 6.0.7 on 2026-07-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin')], default='CLIENT', max_length=20),
        ),
    ]
