# Generated by Django 6.0.7 on 2026-07-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_address_and_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(blank='', default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='institution_number',
            field=models.CharField(blank='', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank='', default='', max_length=20),
        ),
    ]
