# Generated by Django 6.0.7 on 2026-07-26 01:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('fields', '0002_alter_field_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date'], name='bookings_bo_date_e2d163_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'date'], name='bookings_bo_user_id_4a9385_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['field', 'date'], name='bookings_bo_field_i_de5fc7_idx'),
        ),
    ]
