# Generated by Django 6.0.7 on 2026-07-26 01:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_bookings_bo_date_e2d163_idx_and_more'),
        ('fields', '0003_field_deleted_at_field_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['deleted_at'], name='bookings_bo_deleted_9adab7_idx'),
        ),
    ]
